spring:
  config:
    name: ms-gf-cart-service
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
        uri: ${MONGODB_URI:mongodb://localhost:27017/greenfood-cart-service}
server:
  port: 8090